import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecopunto Incidencia App',
  description: 'Generated by Propelland for Ecovidrio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      {/*<body className={`${inter.className} max-w-md mx-auto`}>{children}</body>*/}
      <body className='inter.className'>{children}</body>
    </html>
  )
}
